[package]
org = "wso2"
name = "pas_payer_backend"
version = "0.1.0"
distribution = "2201.13.1"

[build-options]
observabilityIncluded = true

# [[dependency]]
# org = "ballerinax"
# name = "health.fhir.r4"
# version = "5.2.2"

# [[dependency]]
# org = "ballerinax"
# name = "health.fhir.r4.international401"
# version = "4.0.0"

# [[dependency]]
# org = "ballerinax"
# name = "health.clients.fhir"
# version = "1.1.0"

[[dependency]]
org = "ballerinax"
name = "health.fhirr4"
version = "3.0.3"
repository="local"